spring.application.name=demointernetdb
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=1
spring.datasource.url=jdbc:postgresql://ep-fancy-breeze-amz7icm0-pooler.c-5.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_bkyJYcU8HO4A&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bkyJYcU8HO4A